engines:
  eslint:
    enabled: true
    channel: "eslint-8"
    config:
      config: .eslintrc.js
      extensions:
      - .js
      - .jsx

exclude_paths:
- .github/
- .husky/

checks:
 similar-code:
    enabled: false
