version: "2" 
# engines:
#   eslint:
#     enabled: true
#     channel: "eslint-8"
#     config:
#       config: .eslintrc.js
#       extensions:
#       - .ts
#       - .tsx

exclude_paths:
- .github/
- .husky/
- "**/*.js"

checks:
  similar-code:
    enabled: true
    config:
      threshold: 45
  identical-code:
    enabled: true
    config:
      threshold: 45
