engines:
  eslint:
    enabled: true
    channel: "eslint-8"
    config:
      config: .eslintrc.js
      extensions:
      - .js
      - .jsx
      - .ts
      - .tsx

exclude_paths:
- .github/
- .husky/
- "**/*.js"

checks:
 similar-code:
    enabled: true
