import type { MetadataRoute } from 'next'

import { DOMAIN } from '../process.env/domain'

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = `https://${DOMAIN}`
  return [
    {
      url: `${baseUrl}`,
      lastModified: new Date().toISOString().split('T')[0],
      changeFrequency: 'daily',
      priority: 0.8,
      images: [],
      videos: [],
    },
    {
      url: `${baseUrl}/en`,
      lastModified: new Date().toISOString().split('T')[0],
      changeFrequency: 'daily',
      priority: 0.8,
      images: [],
      videos: [],
    },
    {
      url: `${baseUrl}/privacy-policy`,
      lastModified: new Date().toISOString().split('T')[0],
      changeFrequency: 'monthly',
      priority: 0.3,
      images: [],
      videos: [],
    },
    {
      url: `${baseUrl}/en/privacy-policy`,
      lastModified: new Date().toISOString().split('T')[0],
      changeFrequency: 'monthly',
      priority: 0.3,
      images: [],
      videos: [],
    },
    {
      url: `${baseUrl}/categories`,
      lastModified: new Date().toISOString().split('T')[0],
      changeFrequency: 'daily',
      priority: 0.8,
      images: [],
      videos: [],
    },
    {
      url: `${baseUrl}/en/categories`,
      lastModified: new Date().toISOString().split('T')[0],
      changeFrequency: 'daily',
      priority: 0.8,
      images: [],
      videos: [],
    },
    {
      url: `${baseUrl}/recipe/shashlyk-iz-svininy-na-kefire`,
      lastModified: new Date().toISOString().split('T')[0],
      changeFrequency: 'monthly',
      priority: 0.8,
      images: [],
      videos: [],
    },
    {
      url: `${baseUrl}/en/recipe/shashlyk-iz-svininy-na-kefire`,
      lastModified: new Date().toISOString().split('T')[0],
      changeFrequency: 'monthly',
      priority: 0.8,
      images: [],
      videos: [],
    },
    {
      url: `${baseUrl}/recipe/shashlyk-iz-kurinogo-bedra`,
      lastModified: new Date().toISOString().split('T')[0],
      changeFrequency: 'monthly',
      priority: 0.8,
      images: [],
      videos: [],
    },
    {
      url: `${baseUrl}/en/recipe/shashlyk-iz-kurinogo-bedra`,
      lastModified: new Date().toISOString().split('T')[0],
      changeFrequency: 'monthly',
      priority: 0.8,
      images: [],
      videos: [],
    },
    {
      url: `${baseUrl}/recipe/grecheskij-salat`,
      lastModified: new Date().toISOString().split('T')[0],
      changeFrequency: 'monthly',
      priority: 0.8,
      images: [],
      videos: [],
    },
    {
      url: `${baseUrl}/en/recipe/grecheskij-salat`,
      lastModified: new Date().toISOString().split('T')[0],
      changeFrequency: 'monthly',
      priority: 0.8,
      images: [],
      videos: [],
    },
    {
      url: `${baseUrl}/recipe/scrambled-eggs`,
      lastModified: new Date().toISOString().split('T')[0],
      changeFrequency: 'monthly',
      priority: 0.8,
      images: [],
      videos: [],
    },
    {
      url: `${baseUrl}/en/recipe/scrambled-eggs`,
      lastModified: new Date().toISOString().split('T')[0],
      changeFrequency: 'monthly',
      priority: 0.8,
      images: [],
      videos: [],
    },
    {
      url: `${baseUrl}/recipe/scrambled-eggs-with-broccoli`,
      lastModified: new Date().toISOString().split('T')[0],
      changeFrequency: 'monthly',
      priority: 0.8,
      images: [],
      videos: [],
    },
    {
      url: `${baseUrl}/en/recipe/scrambled-eggs-with-broccoli`,
      lastModified: new Date().toISOString().split('T')[0],
      changeFrequency: 'monthly',
      priority: 0.8,
      images: [],
      videos: [],
    },
    {
      url: `${baseUrl}/recipe/borshch-s-pampushkami`,
      lastModified: new Date().toISOString().split('T')[0],
      changeFrequency: 'monthly',
      priority: 0.8,
      images: [],
      videos: [],
    },
    {
      url: `${baseUrl}/en/recipe/borshch-s-pampushkami`,
      lastModified: new Date().toISOString().split('T')[0],
      changeFrequency: 'monthly',
      priority: 0.8,
      images: [],
      videos: [],
    },
  ]
}
