name: "ESLint"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 1' # Every Monday at 00:00 UTC

jobs:
  build:
    name: Analyze
    runs-on: ubuntu-latest
    # Permissions scoped to the job (no top-level permissions)
    permissions:
      actions: read
      contents: read
      security-events: write  # Write access is explicitly granted here
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: yarn

      - name: Lint
        run: yarn lint